### PR TITLE
Update cookiecutter doc url

### PR DESCRIPTION
**Pull request by mgermain**

### CODE REVIEW

**Review by mirkobronzi — APPROVED** [review]

**Comment by mirkobronzi** [comment]
@mgermain : could you change the target branch to master?
for the rest it's ok - thanks a lot for spotting  this :)

**Comment by mgermain** [comment]
> @mgermain : could you change the target branch to master?
> for the rest it's ok - thanks a lot for spotting this :)

The target branch is master, do you mean develop?

**Comment by mirkobronzi** [comment]
> > @mgermain : could you change the target branch to master?
> > for the rest it's ok - thanks a lot for spotting this :)
> 
> The target branch is master, do you mean develop?

yes sorry - develop :)

**Comment by mgermain** [comment]
> > > @mgermain : could you change the target branch to master?
> > > for the rest it's ok - thanks a lot for spotting this :)
> > 
> > 
> > The target branch is master, do you mean develop?
> 
> yes sorry - develop :)

Done!

**Pull request closed without merging**
